CREATE TABLE events (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title             VARCHAR(255)  NOT NULL,
    event_type        VARCHAR(20)   NOT NULL,
    region            VARCHAR(20)   NOT NULL,
    platform          VARCHAR(255)  NOT NULL,
    original_url      VARCHAR(1000) NOT NULL,
    description       TEXT,
    cover_image_url   VARCHAR(1000),
    publisher         VARCHAR(255),
    start_at          TIMESTAMP,
    end_at            TIMESTAMP,
    goal_amount       NUMERIC(15, 2),
    current_amount    NUMERIC(15, 2),
    currency          VARCHAR(3),
    moderation_status VARCHAR(20)   NOT NULL,
    rejection_reason  VARCHAR(500),
    submitter_name    VARCHAR(255),
    submitter_email   VARCHAR(255),
    created_at        TIMESTAMP     NOT NULL,
    updated_at        TIMESTAMP     NOT NULL
);

CREATE INDEX idx_events_moderation_end ON events (moderation_status, end_at);
CREATE INDEX idx_events_region ON events (region);
CREATE INDEX idx_events_type ON events (event_type);
