CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider     VARCHAR(20)  NOT NULL,
    provider_id  VARCHAR(255) NOT NULL,
    email        VARCHAR(255),
    display_name VARCHAR(255) NOT NULL,
    role         VARCHAR(20)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    CONSTRAINT uk_users_provider_id UNIQUE (provider, provider_id)
);

ALTER TABLE events ADD COLUMN submitted_by_user_id BIGINT REFERENCES users (id);
