CREATE TABLE games (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_ko       VARCHAR(255),
    title_original VARCHAR(255) NOT NULL,
    publisher      VARCHAR(255),
    bgg_id         BIGINT,
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL
);

ALTER TABLE events ADD COLUMN schedule_note VARCHAR(255);
ALTER TABLE events ADD COLUMN game_id BIGINT REFERENCES games (id);
ALTER TABLE events ADD COLUMN location VARCHAR(255);
ALTER TABLE events ADD COLUMN address VARCHAR(500);
ALTER TABLE events ADD COLUMN admission_fee NUMERIC(15, 2);
ALTER TABLE events ADD COLUMN reservation_url VARCHAR(1000);

-- Pre-launch, no production data to backfill: funding progress fields are dropped outright (see PRD §4.1).
ALTER TABLE events DROP COLUMN goal_amount;
ALTER TABLE events DROP COLUMN current_amount;
ALTER TABLE events DROP COLUMN currency;
