CREATE TABLE bookmarks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL REFERENCES users (id),
    event_id   BIGINT    NOT NULL REFERENCES events (id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_bookmarks_user_event UNIQUE (user_id, event_id)
);

CREATE INDEX idx_bookmarks_user ON bookmarks (user_id);
